config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :fighters, only: [:new, :create, :edit, :update, :destroy]
  resources :fights, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipement.rb
class Equipement < ApplicationRecord
  def decorate_for_form
    [id, "#{name} (Attack: +#{attack_points}, Defense: +#{defense_points})"]
  end
end

app/models/fight.rb
class Fight < ApplicationRecord
  belongs_to :winner, class_name: 'Fighter', optional: true
  belongs_to :loser, class_name: 'Fighter', optional: true

  has_many :strokes, dependent: :destroy
  has_many :fight_fighters, dependent: :destroy, index_errors: true
  has_many :fighters, through: :fight_fighters

  accepts_nested_attributes_for :fight_fighters, allow_destroy: true

  validates_associated :fight_fighters
  validate :check_different_fighters

  after_create :run_fight

  private

  def check_different_fighters
    first_fighter_id = nil
    fight_fighters.each do |fight_fighter|
      if first_fighter_id.nil?
        first_fighter_id = fight_fighter.fighter_id
      elsif first_fighter_id == fight_fighter.fighter_id
        errors['fight_fighters[0].fighter'] << "you should choose two different fighters!"
      end
    end
  end

  def run_fight
    fighter_1 = fight_fighters[0]
    fighter_2 = fight_fighters[1]

    current_player = rand(2) # chooses randomly first player

    until strokes.where(missed: false, target: fighter_1.fighter).map(&:impact).sum >= fighter_1.fighter.life_points ||
          strokes.where(missed: false, target: fighter_2.fighter).map(&:impact).sum >= fighter_2.fighter.life_points

      if current_player.even?
        Stroke.create(fight: self, owner: fighter_2.fighter, target: fighter_1.fighter, attack_equipement: fighter_2.equipement, defense_equipement: fighter_1.equipement)
      else
        Stroke.create(fight: self, owner: fighter_1.fighter, target: fighter_2.fighter, attack_equipement: fighter_1.equipement, defense_equipement: fighter_2.equipement)
      end

      current_player += 1
    end

    if strokes.where(missed: false, target: fighter_1.fighter).map(&:impact).sum >= fighter_1.fighter.life_points
      loser, winner = fighter_1.fighter, fighter_2.fighter
    else
      loser, winner = fighter_2.fighter, fighter_1.fighter
    end

    update(winner: winner, loser: loser)
    winner.increment!(:experience)
  end
end

app/models/fight_fighter.rb
class FightFighter < ApplicationRecord
  belongs_to :fight, optional: true
  belongs_to :fighter
  belongs_to :equipement

  validates :fighter, :equipement, presence: true
end

app/models/fighter.rb
class Fighter < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  has_many :won_fights, class_name: 'Fight', foreign_key: 'winner_id', dependent: :destroy
  has_many :lost_fights, class_name: 'Fight', foreign_key: 'loser_id', dependent: :destroy

  has_many :given_strokes, class_name: 'Stroke', foreign_key: 'owner_id', dependent: :destroy
  has_many :received_strokes, class_name: 'Stroke', foreign_key: 'target_id', dependent: :destroy

  has_many :fight_fighters, dependent: :destroy

  validates :name, :life_points, :attack_points, presence: true
  validates :name, uniqueness: true
  validates :name, length: { minimum: 3 }
  validates :life_points, :attack_points, inclusion: { in: ((1..99)),
  message: "should be between 1 and 99" }
  validate :sum_equals_100

  def percentage_of_victory
    if won_fights.any? || lost_fights.any?
      total_fights = (won_fights + lost_fights).count
      stat = won_fights.count * 100 / total_fights
      "#{stat} % (#{total_fights})"
    else
      'Never fought'
    end
  end

  def decorate_for_form
    [id, "#{name} (Life: #{life_points}, Attack: #{attack_points})"]
  end

  private

  def sum_equals_100
    return unless life_points + attack_points != 100

    errors.add(:life_points, "The sum of your life points and attack points should be equal to 100")
    errors.add(:attack_points, "The sum of your life points and attack points should be equal to 100")
  end
end

app/models/fighter_equipement.rb
class FighterEquipement < ApplicationRecord
  belongs_to :fighter
  belongs_to :equipement
end

app/models/stroke.rb
class Stroke < ApplicationRecord
  belongs_to :fight
  belongs_to :owner, class_name: 'Fighter'
  belongs_to :target, class_name: 'Fighter'
  belongs_to :attack_equipement, class_name: 'Equipement'
  belongs_to :defense_equipement, class_name: 'Equipement'

  after_create :run_strike

  RNG = 10 # to add a little chance in the outcome of the fights

  def decorated
    if missed
      "#{owner.name} missed #{target.name}"
    else
      "#{owner.name} inflicted #{impact} points of damage to #{target.name}"
    end
  end

  private

  def run_strike
    update(impact: owner.attack_points + attack_equipement.attack_points - defense_equipement.defense_points)
    update(missed: true) if rand(RNG) == 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  before_action :set_fighter, only: [:edit, :update, :destroy]

  def index
    @fighters = Fighter.all
  end

  def new
    @fighter = Fighter.new
  end

  def create
    @fighter = Fighter.new(fighter_params)
    if @fighter.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @fighter.assign_attributes(fighter_params)
    if @fighter.save
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @fighter.destroy
    redirect_to root_path
  end

  private

  def fighter_params
    params.require(:fighter).permit(:name, :life_points, :attack_points, :photo)
  end

  def set_fighter
    @fighter = Fighter.find(params[:id])
  end
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  def new
    @fighters = Fighter.all.map(&:decorate_for_form)
    @equipements = Equipement.all.map(&:decorate_for_form)
    @fight = Fight.new
    2.times do
      @fight.fight_fighters.build
    end
  end

  def create
    @fight = Fight.new(fight_params)

    @fighters = Fighter.all.map(&:decorate_for_form)
    @equipements = Equipement.all.map(&:decorate_for_form)

    if @fight.save
      redirect_to fight_path(@fight)
    else
      render 'new'
    end
  end

  def show
    @fight = Fight.find(params[:id])
    @strikes = Stroke.where(fight: @fight).order(created_at: :asc)
  end

  private

  def fight_params
    params.require(:fight).permit(:name, fight_fighters_attributes: [:fighter_id, :equipement_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @fighters = Fighter.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fighters/_form.html.erb
<%= simple_form_for fighter do |f| %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.input :name, required: true, placeholder: "Pikachu" %>
  <%= f.input :life_points, required: true, collection: 1..99 %>
  <%= f.input :attack_points, required: true, collection: 1..99 %>

  <div class="form-actions">
    <%= f.button :submit, "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/fighters/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 offset-sm-3">
      <div class="form">
        <%= render 'fighters/form', fighter: @fighter %>
      </div>
    </div>
  </div>
</div>

app/views/fighters/index2.html.erb
<div class="page-container">

  <%= link_to 'Create a new fighter', new_fighter_path, class:'btn btn-primary btn-lg' %>

  <% if @fighters.any? %>
    <form id="fighter-choices">

      <div class="row">
        <% @fighters.each do |fighter| %>
          <div class="col-xs-12 col-md-6">
            <input type="checkbox" value="<%= fighter.id %>" id="<%= fighter.id %>">
            <label for="<%= fighter.id %>" class="fighter-choice fighter-card-<%= fighter.id %>  ">
              <%= cl_image_tag fighter.photo, height: 100, width: 100, crop: :fill, class:'avatar-small' %>
              <p><%= fighter.name %></p>
              <p><%= fighter.life_points %></p>
              <p><%= fighter.attack_points %></p>

              <%= link_to edit_fighter_path(fighter.id) do %>
                <i class="fas fa-pen"></i>
              <% end %>

              <%= link_to fighter_path(fighter.id) do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </label>
          </div>
        <% end %>
      </div>

      <input type="submit" class="btn btn-primary" value="Validate my choice">
    </form>

  <% else %>
    <p>No fighters</p>
  <% end %>

</div>

<script type="text/javascript">
  document.querySelectorAll('input').forEach(function(element) {
    element.addEventListener('change', function(event) {
      if (document.querySelectorAll('input:checked').length > 2)  {
        event.currentTarget.checked = false
        alert("Please select 2 fighters")
      } else {
        let currentFighter = event.currentTarget.value
        document.querySelector('.fighter-card-' + currentFighter).classList.toggle('active')
      }
    })
  })

  const form = document.querySelector('#fighter-choices')
  form.addEventListener('submit', function(event) {
    event.preventDefault();
    if (document.querySelectorAll('input:checked').length == 1) {
      alert("Please select 2 fighters")
    } else {
      var fighter_1 = document.querySelectorAll('input:checked')[0].value
      var fighter_2 = document.querySelectorAll('input:checked')[1].value
      console.log(fighter_1, fighter_2)
    }
  } )
</script>

app/views/fighters/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 offset-sm-3">
      <div class="form">
        <%= render 'fighters/form', fighter: @fighter %>
      </div>
    </div>
  </div>
</div>

app/views/fights/new.html.erb
<% @fight.errors.full_messages.each do |text| %>
  <p><%= text %></p>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 offset-sm-3">
      <div class="form">
        <%= simple_form_for @fight do |f| %>
          <%= f.simple_fields_for :fight_fighters do |ff| %>
            <%= ff.input :fighter_id, required: true, collection: @fighters, label_method: :second, value_method: :first %>
            <%= ff.input :equipement_id, required: true, collection: @equipements, label_method: :second, value_method: :first %>
          <% end %>
          <div class="form-actions">
            <%= f.button :submit, "Start the fight", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/fights/show.html.erb
<h1>Winner: <%= @fight.winner.name %></h1>
<h4>Life points: <%= @fight.winner.life_points %></h1>
<h4>Attack points: <%= @fight.winner.attack_points %></h1>
<h4>Equipement: Attack: <%= @fight.fight_fighters.find_by(fighter: @fight.winner).equipement.attack_points %></h1>
<h4>Equipement: Defense: <%= @fight.fight_fighters.find_by(fighter: @fight.winner).equipement.defense_points %></h1>


<h1>Loser: <%= @fight.loser.name %></h1>
<h4>Life points: <%= @fight.loser.life_points %></h1>
<h4>Attack points: <%= @fight.loser.attack_points %></h1>
<h4>Equipement: Attack: <%= @fight.fight_fighters.find_by(fighter: @fight.loser).equipement.attack_points %></h1>
<h4>Equipement: Defense: <%= @fight.fight_fighters.find_by(fighter: @fight.loser).equipement.defense_points %></h1>


<% @strikes.each do |strike| %>
  <p><%= strike.decorated %></p>
<% end %>

<%= link_to 'Back to home page', root_path, class:'btn btn-primary btn-lg' %>
<%= link_to 'New fight', new_fight_path, class:'btn btn-primary btn-lg' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Welcome!</h1>
    <%= link_to 'Start a fight', new_fight_path, class:'btn btn-primary btn-lg' %>
  </div>
</div>

<div class="fighters-index">
  <h1 class="text-center">All Fighters</h1>
  <div class="row margin-40px">
    <% @fighters.each do |fighter| %>
      <div class="col-xs-12 col-md-6">
        <div class="fighter-card margin-10px d-flex">
          <div class="fighter-photo">
            <%= cl_image_tag fighter.photo, height: 100, width: 100, crop: :fill, class:'avatar-small' %>
          </div>
          <div class="fighter-main-infos">
            <p class="no-margin-bottom text-bold"><%= fighter.name %></p>
            <p class="no-margin-bottom">Life points: <%= fighter.life_points %></p>
            <p class="no-margin-bottom">Attack points: <%= fighter.attack_points %></p>
          </div>
          <div class="fighter-stat">
            <p class="no-margin-bottom">Victory rate:</p>
            <p class="no-margin-bottom"><%= fighter.percentage_of_victory %></p>
          </div>
          <div class="btns margin-auto">
            <%= link_to edit_fighter_path(fighter.id) do %>
              <i class="fas fa-pen"></i>
            <% end %>

            <%= link_to fighter_path(fighter.id), method: :delete do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="col-xs-12 col-md-6">
      <%= link_to new_fighter_path do %>
        <div class="fighter-card margin-10px d-flex justify-content-center">
          <%= image_tag 'add.png' %>
        </div>
      <% end %>
    </div>
  </div>
</div>